// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: api_tokens.sql

package sqlc

import (
	"context"

	"go.robinthrift.com/belt/internal/domain"
	"go.robinthrift.com/belt/internal/storage/database/sqlite/types"
)

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens(
    account_id,
    token_id,
	name,
    expires_at
) VALUES (?, ?, ?, ?)
`

type CreateAPITokenParams struct {
	AccountID domain.AccountID
	TokenID   int64
	Name      string
	ExpiresAt types.SQLiteDatetime
}

func (q *Queries) CreateAPIToken(ctx context.Context, db DBTX, arg CreateAPITokenParams) error {
	_, err := db.ExecContext(ctx, createAPIToken,
		arg.AccountID,
		arg.TokenID,
		arg.Name,
		arg.ExpiresAt,
	)
	return err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE name = ? AND account_id = ?
`

type DeleteAPITokenParams struct {
	Name      string
	AccountID domain.AccountID
}

func (q *Queries) DeleteAPIToken(ctx context.Context, db DBTX, arg DeleteAPITokenParams) error {
	_, err := db.ExecContext(ctx, deleteAPIToken, arg.Name, arg.AccountID)
	return err
}

const getAPIToken = `-- name: GetAPIToken :one
SELECT id, account_id, token_id, name, created_at, expires_at FROM api_tokens WHERE name = ? AND account_id = ? LIMIT 1
`

type GetAPITokenParams struct {
	Name      string
	AccountID domain.AccountID
}

func (q *Queries) GetAPIToken(ctx context.Context, db DBTX, arg GetAPITokenParams) (ApiToken, error) {
	row := db.QueryRowContext(ctx, getAPIToken, arg.Name, arg.AccountID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenID,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, account_id, token_id, name, created_at, expires_at
FROM api_tokens
WHERE id > ?1
AND account_id = ?2
ORDER BY id DESC
LIMIT ?3
`

type ListAPITokensParams struct {
	PageAfter domain.APITokenID
	AccountID domain.AccountID
	PageSize  int64
}

func (q *Queries) ListAPITokens(ctx context.Context, db DBTX, arg ListAPITokensParams) ([]ApiToken, error) {
	rows, err := db.QueryContext(ctx, listAPITokens, arg.PageAfter, arg.AccountID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenID,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
