// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"go.robinthrift.com/conveyor/internal/auth"
	"go.robinthrift.com/conveyor/internal/domain"
	"go.robinthrift.com/conveyor/internal/storage/database/sqlite/types"
)

type Account struct {
	ID                     domain.AccountID
	Username               string
	Algorithm              string
	Params                 string
	Salt                   []byte
	Password               []byte
	RequiresPasswordChange bool
	CreatedAt              types.SQLiteDatetime
	UpdatedAt              types.SQLiteDatetime
}

type AccountKey struct {
	ID        int64
	AccountID int64
	Name      string
	Type      string
	Data      []byte
	CreatedAt string
	UpdatedAt string
}

type ApiToken struct {
	ID        domain.APITokenID
	AccountID domain.AccountID
	TokenID   int64
	Name      string
	CreatedAt types.SQLiteDatetime
	ExpiresAt types.SQLiteDatetime
}

type AuthToken struct {
	ID               auth.AuthTokenID
	AccountID        domain.AccountID
	Value            []byte
	ExpiresAt        types.SQLiteDatetime
	RefreshValue     []byte
	RefreshExpiresAt types.SQLiteDatetime
	IsValid          bool
	CreatedAt        types.SQLiteDatetime
}

type ChangelogEntry struct {
	ID           domain.ChangelogEntryID
	AccountID    domain.AccountID
	SyncClientID domain.SyncClientID
	Data         []byte
	Timestamp    types.SQLiteDatetime
}

type FullSyncEnrire struct {
	ID        int64
	AccountID domain.AccountID
	Timestamp types.SQLiteDatetime
	SizeBytes int64
	Sha256    []byte
}

type Job struct {
	ID           int64
	State        interface{}
	Kind         string
	Data         types.SQLiteJSON
	Result       types.SQLiteJSON
	ScheduledFor types.SQLiteDatetime
	CreatedAt    types.SQLiteDatetime
	FinishedAt   types.SQLiteDatetime
}

type SyncClient struct {
	ID        int64
	PublicID  domain.SyncClientID
	AccountID domain.AccountID
	CreatedAt types.SQLiteDatetime
	UpdatedAt types.SQLiteDatetime
}
