version: "2"
linters:
  default: all
  disable:
  - zerologlint # Disabled, because I usually don't use zerolog
  - ginkgolinter # Disabled, because I usually don't use ginkgo or gomega
  - loggercheck # Disabled, becuse I usually don't use any of kitlog, klog, logr, zap
  - testpackage # Disabled, because I usually don't always want to use a separate _test pacakge
  - depguard # Disabled because it's too restrictive
  - gomoddirectives # Disabled, too restrictive
  - exhaustruct # Disabled, because it's generally good design to have defaults that make sense
  - wrapcheck # Disable for now, maybe enable again later
  - tagliatelle # Disabled, config is too complicated for the added value
  - nonamedreturns
  - lll
  - ireturn # Disabled, because too restrictive
  settings:
    sloglint:
      no-mixed-args: true
      attr-only: true
      static-msg: false
      key-naming-case: snake
      forbidden-keys:
        - time
        - level
        - msg
      args-on-sep-lines: false
    varnamelen:
      max-distance: 30
      check-receiver: false
      check-return: false
      check-type-param: false
      ignore-names:
        - err
        - id
        - tx
        - db
        - tt
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - t testing.T
        - e error
        - i int
        - T any
        - w http.ResponseWriter
        - r *http.Request
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
    - path: _test\.go
      linters:
      - funlen
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
