// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tags.sql

package sqlc

import (
	"context"
)

const cleanupTagsWithNoCount = `-- name: CleanupTagsWithNoCount :exec
DELETE FROM tags WHERE count = 0
`

func (q *Queries) CleanupTagsWithNoCount(ctx context.Context, db DBTX) error {
	_, err := db.ExecContext(ctx, cleanupTagsWithNoCount)
	return err
}

const createMemoTagConnection = `-- name: CreateMemoTagConnection :exec
INSERT INTO memo_tags(
    memo_id,
    tag
) VALUES (?, ?)
ON CONFLICT (memo_id, tag) DO NOTHING
`

type CreateMemoTagConnectionParams struct {
	MemoID int64
	Tag    string
}

func (q *Queries) CreateMemoTagConnection(ctx context.Context, db DBTX, arg CreateMemoTagConnectionParams) error {
	_, err := db.ExecContext(ctx, createMemoTagConnection, arg.MemoID, arg.Tag)
	return err
}

const createTag = `-- name: CreateTag :exec
INSERT INTO tags(
    tag,
    count
) VALUES (?, ?)
ON CONFLICT (tag)
DO UPDATE SET
    count       = count+1,
    updated_at  = strftime('%Y-%m-%d %H:%M:%SZ', CURRENT_TIMESTAMP)
`

type CreateTagParams struct {
	Tag   string
	Count int64
}

func (q *Queries) CreateTag(ctx context.Context, db DBTX, arg CreateTagParams) error {
	_, err := db.ExecContext(ctx, createTag, arg.Tag, arg.Count)
	return err
}

const deleteMemoTagConnection = `-- name: DeleteMemoTagConnection :exec
DELETE FROM memo_tags WHERE memo_id = ? AND tag = ?
`

type DeleteMemoTagConnectionParams struct {
	MemoID int64
	Tag    string
}

func (q *Queries) DeleteMemoTagConnection(ctx context.Context, db DBTX, arg DeleteMemoTagConnectionParams) error {
	_, err := db.ExecContext(ctx, deleteMemoTagConnection, arg.MemoID, arg.Tag)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
UPDATE tags SET
    count      = count-1,
    updated_at = strftime('%Y-%m-%d %H:%M:%SZ', CURRENT_TIMESTAMP)
WHERE tag IN (?)
`

func (q *Queries) DeleteTag(ctx context.Context, db DBTX, tag string) error {
	_, err := db.ExecContext(ctx, deleteTag, tag)
	return err
}

const listTags = `-- name: ListTags :many
SELECT id, tag, count, created_by, created_at, updated_at
FROM tags
WHERE tag > ?1
ORDER BY tag DESC
LIMIT ?2
`

type ListTagsParams struct {
	After string
	Limit int64
}

func (q *Queries) ListTags(ctx context.Context, db DBTX, arg ListTagsParams) ([]Tag, error) {
	rows, err := db.QueryContext(ctx, listTags, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.Count,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
